### ISSUE TITLE
Toggle Printer Function.

### ISSUE THREAD

**Issue by SmilerRyan** [bsalha1/Printer#11]
With the only commands being on/off, reload and version, a nice addition would be a toggle command.
It would check is they are printing or not, and if they have the correct on/off permission.
This would allow other servers ([such as ours](https://accretion.ga)) to easilly create a custom command.

**Comment by bsalha1** [comment]
Okay I can do that

**Comment by bsalha1** [comment]
I added the toggle command - here is the link for the update (2.6) [https://www.spigotmc.org/resources/printer.79811/history](url)
