### ISSUE TITLE
Printer enabled anywhere

### ISSUE THREAD

**Issue by Drc-DEV** [bsalha1/Printer#9]
While in printer mode, players can fly outside their claims, even if printer is only enabled in their claims by config. Expected behaviour would be to limit the printer mode to their claims

Using Printer v2.4 and FactionsX

**Comment by bsalha1** [comment]
This was an issue I have fixed, I have not released it yet, I'm working on a hook for Lands and then I will release it.

**Comment by bsalha1** [comment]
[https://www.mediafire.com/file/luymh94hgrrmewo/Printer-LATEST.jar/file](url) here is the current build since it's taking too long for me to figure out how to make a working Lands hook, this will fix your issue though. Let me know if it works.
